In [1]:
import pandas as pd;

In [4]:
insurance_data=pd.read_csv("insurance.csv")
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [9]:
#One Hot encoding

X = insurance_data.drop(columns=["charges"])
y = insurance_data["charges"]

X=pd.get_dummies(X,columns=["region"],drop_first=True) #true for multicolinearality

X["sex"] = X["sex"].map({"female": 1, "male": 0})
X["smoker"] = X["smoker"].map({"yes": 1, "no": 0})

X.head()

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
0,19,1,27.900,0,1,False,False,True
1,18,0,33.770,1,0,False,True,False
2,28,0,33.000,3,0,False,True,False
3,33,0,22.705,0,0,True,False,False
4,32,0,28.880,0,0,True,False,False

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("r-squared:", r2)

r-squared: 0.7835929767120724

In [11]:
#Create useful derived feature

In [12]:
#Interaction Feature
X = insurance_data.drop(columns=["charges"])
y = insurance_data["charges"]

X=pd.get_dummies(X,columns=["region"],drop_first=True) #true for multicolinearality

X["sex"] = X["sex"].map({"female": 1, "male": 0})
X["smoker"] = X["smoker"].map({"yes": 1, "no": 0})

X["age_smoker"]=X["age"]*X["smoker"];
X["bmi_smoker"]=X["bmi"]*X["smoker"];

X.head()

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest,age_smoker,bmi_smoker
0,19,1,27.900,0,1,False,False,True,19,27.9
1,18,0,33.770,1,0,False,True,False,0,0.0
2,28,0,33.000,3,0,False,True,False,0,0.0
3,33,0,22.705,0,0,True,False,False,0,0.0
4,32,0,28.880,0,0,True,False,False,0,0.0